export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'  
export { default as Header } from './Header/Header'
export { default as Skills } from './Skills/Skills'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Works } from './Works/Works'
export { default as Family } from './Gallery/Family'
export { default as Wedding } from './Gallery/Wedding'
export { default as Kids } from './Gallery/Kids'
export { default as Engagement } from './Gallery/Engagement'
export { default as Maternity } from './Gallery/Maternity'
export { default as Branding } from './Gallery/Branding'
export { default as HomeCarousels } from './Carousel/HomeCarousels'
export { default as PhotoCategory } from './Gallery/PhotoCategory'

