export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'  
export { default as Footer2 } from './Footer/Footer2'  
export { default as Header } from './Header/Header'
export { default as GalleryModel } from './Gallery/Gallery'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Project } from './Project/Project'
export { default as Gallery } from './Gallery/Gallery'
export { default as VideoPlayer } from './VideoPlayer/VideoPlayer'
export { Counter } from './Counter/Counter'

